### ISSUE TITLE
CreateEvents: Add Location selection

### ISSUE THREAD

**Issue by cinnayre** [sopra-fs23-group-07/sopra-fs23-group-07-client#102]

**Comment by oaboha** [comment]
https://github.com/sopra-fs23-group-07/sopra-fs23-group-07-client/commit/220741d963220315613e77bf07f8e96d41e11851

**Comment by oaboha** [comment]
https://github.com/sopra-fs23-group-07/sopra-fs23-group-07-client/commit/220741d963220315613e77bf07f8e96d41e11851
