### ISSUE TITLE
Bug fix: Header should update if user logs in or out

### ISSUE THREAD

**Issue by cinnayre** [sopra-fs23-group-07/sopra-fs23-group-07-client#52]
Before the Header updates you need to reload the page which should be the case. There is a comment about it in the header file. Most relevant files are header.js and NavbarLoggedIn.js

**Comment by oaboha** [comment]
https://github.com/sopra-fs23-group-07/sopra-fs23-group-07-client/commit/7ff408d88fce09ba18ab7e9577d99c9b9196e992
